export const settings = {
    apiBaseUrl: import.meta.env.VITE_API_BASE,
    baseUrl: import.meta.env.VITE_BASE_URL,
    authUrl: import.meta.env.VITE_LOGIN_URL,
    autLogoutUrl: import.meta.env.VITE_LOGOUT_URL,
    createCLientUrl: import.meta.env.VITE_CREATE_CLIENT_URL,
    timeoutRefresh: import.meta.env.VITE_TIMEOUTREFRESH,
    routeGomain: import.meta.env.VITE_ROUTES_GOMAIN,
    routeOrders: import.meta.env.VITE_ROUTES_ORDERS,
    routeMenu: import.meta.env.VITE_ROUTES_MENU,
    routeWaiters: import.meta.env.VITE_ROUTES_WAITERS,
    routeTables: import.meta.env.VITE_ROUTES_TABLES,
    routeBookings: import.meta.env.VITE_ROUTES_BOOKINGS,
    routeBillings: import.meta.env.VITE_ROUTES_BILLINGS,
}